fun main() {

    print("Student Enrollment No.: ")
    val enrNo = readln()
    print("Student Name: ")
    val name = readln()
    print("Student Branch: ")
    val branch = readln()
    print("Student Class: ")
    val stdntClass = readln()
    print("Student Batch: ")
    val batch = readln()
    print("Student College Name: ")
    val collegeName = readln()
    print("Student University Name: ")
    val universityName = readln()
    print("Student Age: ")
    val age = readln()

    println("******************************")
    println("Student's Data:")
    println("Enrollment No.: $enrNo")
    println("Name: $name")
    println("Age: $age")
    println("Branch: $branch")
    println("Class: $stdntClass")
    println("Batch: $batch")
    println("College Name: $collegeName")
    println("University Name: $universityName")

}